version: 1.0
provider:
  name: openfaas
functions:
  database:
    lang: golang-middleware
    handler: ./database
    image: e8kor/crawler:database
    limits:
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      PG_HOST: "database-postgresql.database"
      PG_PORT: "5432"
      exec_timeout: "3m"
    secrets:
      - database-name
      - database-username
      - database-password
    labels:
      com.openfaas.scale.min: 1
      app: "function"
  storage:
    lang: golang-middleware
    handler: ./storage
    image: e8kor/crawler:storage
    limits:
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      MINIO_HOST: "external-storage.storage:9000"
      exec_timeout: "3m"
    secrets:
      - storage-access-key
      - storage-secret-key
    labels:
      com.openfaas.scale.min: 1
      app: "function"
configuration:
  templates:
    - name: golang-middleware