version: 1.0
provider:
  name: openfaas
functions:
  database:
    lang: golang-http
    handler: ./database
    image: e8kor/crawler:database
    limits:
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      PG_HOST: "192.168.0.211"
      PG_PORT: "5432"
      exec_timeout: "1m"
    secrets:
      - database-name
      - database-username
      - database-password
    labels:
      com.openfaas.scale.min: 1
  storage:
    lang: golang-http
    handler: ./storage
    image: e8kor/crawler:storage
    limits:
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      MINIO_HOST: "192.168.0.214:9000"
      exec_timeout: "1m"
    secrets:
      - storage-access-key
      - storage-secret-key
    labels:
      com.openfaas.scale.min: 1
configuration:
  templates:
    - name: golang-middleware