version: 1.0
provider:
  name: openfaas
functions:
  otodom:
    lang: golang-middleware
    handler: ./otodom
    image: e8kor/crawler:otodom
    annotations:
        schedule: "*/5 * * * *"
        topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
  persistor:
    lang: golang-middleware
    handler: ./persistor
    image: e8kor/crawler:persistor
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
configuration:
  templates:
    - name: golang-middleware
    - name: go