version: 1.0
provider:
  name: openfaas
functions:
  database:
    lang: golang-middleware
    handler: ./database
    image: e8kor/crawler:database
    limits:
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      PG_HOST: "external-database"
      PG_PORT: "5432"
      exec_timeout: "1m"
    secrets:
      - database-name
      - database-username
      - database-password
    labels:
      com.openfaas.scale.min: 1
  storage:
    lang: golang-middleware
    handler: ./storage
    image: e8kor/crawler:storage
    limits:
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      MINIO_HOST: "external-storage:9000"
      exec_timeout: "1m"
    secrets:
      - storage-access-key
      - storage-secret-key
    labels:
      com.openfaas.scale.min: 1
  otodom-orchestrator:
    lang: golang-middleware
    handler: ./otodom/orchestrator
    image: e8kor/crawler:otodom-orchestrator
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    annotations:
      schedule: "*/5 * * * *"
      topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      SOURCE_URL: "https://www.otodom.pl/wynajem/lokal/krakow/?search%5Bcity_id%5D=38"
      GATEWAY_URL: "http://gateway.openfaas:8080/function"
      write_timeout: 3m
      read_timeout: 3m
      exec_timeout: 3m
      handler_wait_duration: 1m
  otodom-crawler:
    lang: golang-middleware
    handler: ./otodom/crawler
    image: e8kor/crawler:otodom-crawler
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      exec_timeout: "1m"
    labels:
      com.openfaas.scale.min: 6
configuration:
  templates:
    - name: golang-middleware