version: 1.0
provider:
  name: openfaas
functions:
  otodom-orchestrator:
    lang: golang-http
    handler: ./otodom-orchestrator
    image: e8kor/crawler:otodom-orchestrator
    limits:
      memory: 64Mi
      cpu: 128m
    requests:
      memory: 32Mi
      cpu: 128m
    annotations:
      schedule: "*/5 * * * *"
      topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      SOURCE_URL: "https://www.otodom.pl/wynajem/lokal/krakow/?search%5Bcity_id%5D=38"
      GATEWAY_URL: "http://gateway.openfaas:8080/function"
      exec_timeout: "2100s"
  otodom-scrapper:
    lang: golang-http
    handler: ./otodom-scrapper
    image: e8kor/crawler:otodom-scrapper
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      exec_timeout: "300s"
    labels:
      com.openfaas.scale.min: 2
  database:
    lang: golang-http
    handler: ./database
    image: e8kor/crawler:database
    limits:
      memory: 64Mi
      cpu: 128m
    requests:
      memory: 32Mi
      cpu: 128m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      PG_HOST: "192.168.0.211"
      PG_PORT: "5432"
    secrets:
      - database-name
      - database-username
      - database-password
    labels:
      com.openfaas.scale.min: 2
  storage:
    lang: golang-http
    handler: ./storage
    image: e8kor/crawler:storage
    limits:
      memory: 512Mi
      cpu: 512m
    requests:
      memory: 256Mi
      cpu: 512m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      MINIO_HOST: "192.168.0.214:9000"
      exec_timeout: "300s"
    secrets:
      - storage-access-key
      - storage-secret-key
    labels:
      com.openfaas.scale.min: 2
configuration:
  templates:
    - name: golang-middleware
    - name: golang-http
    - name: go