version: 1.0
provider:
  name: openfaas
functions:
  otodom-orchestrator:
    lang: golang-http
    handler: ./otodom-orchestrator
    image: e8kor/crawler:otodom-orchestrator
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      SOURCE_URL: "https://www.otodom.pl/wynajem/lokal/krakow/?search%5Bcity_id%5D=38&nrAdsPerPage=72"
      GATEWAY_URL: "http://gateway.openfaas:8080/function"
      exec_timeout: "240s"
  otodom-scrapper:
    lang: golang-http
    handler: ./otodom-scrapper
    image: e8kor/crawler:otodom-scrapper
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      exec_timeout: "20s"
    labels:
      com.openfaas.scale.min: 6
  database:
    lang: golang-http
    handler: ./database
    image: e8kor/crawler:database
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      PG_HOST: "192.168.0.211"
      PG_PORT: "5432"
    secrets:
      - database-name
      - database-username
      - database-password
    labels:
      com.openfaas.scale.min: 1
  storage:
    lang: golang-http
    handler: ./storage
    image: e8kor/crawler:storage
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      MINIO_HOST: "192.168.0.214:9000"
      exec_timeout: "60s"
    secrets:
      - storage-access-key
      - storage-secret-key
    labels:
      com.openfaas.scale.min: 1
configuration:
  templates:
    - name: golang-middleware
    - name: golang-http
    - name: go