version: 1.0
provider:
  name: openfaas
functions:
  database:
    lang: golang-middleware
    handler: ./database
    image: e8kor/crawler:database
    limits:
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      PG_HOST: "database-postgresql.database"
      PG_PORT: "5432"
      exec_timeout: "3m"
    secrets:
      - database-name
      - database-username
      - database-password
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.max: 3
      com.openfaas.scale.min: 1
      app: "function"
  storage:
    lang: golang-middleware
    handler: ./storage
    image: e8kor/crawler:storage
    limits:
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      MINIO_HOST: "external-storage.storage:9000"
      exec_timeout: "3m"
    secrets:
      - storage-access-key
      - storage-secret-key
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.max: 5
      com.openfaas.scale.min: 1
      app: "function"
  otodom-office-rent-orchestrator:
    lang: golang-middleware
    handler: ./otodom/orchestrator
    image: e8kor/crawler:otodom-orchestrator
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    annotations:
      schedule: "*/5 * * * *"
      topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      DOMAIN: "otodom-rent"
      CRAWLER_SUFFIX: "/otodom-office-crawler"
      PAGES_SUFFIX: "/otodom-total-pages"
      SOURCE_URL: "https://www.otodom.pl/wynajem/lokal/krakow/?search%5Bcity_id%5D=38"
      GATEWAY_URL: "http://gateway.openfaas:8080/function"
      write_timeout: 5m
      read_timeout: 5m
      exec_timeout: 5m
      handler_wait_duration: 1m
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.max: 2
      com.openfaas.scale.min: 1
      app: "function"
  otodom-office-buy-orchestrator:
    lang: golang-middleware
    handler: ./otodom/orchestrator
    image: e8kor/crawler:otodom-orchestrator
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    annotations:
      schedule: "*/10 * * * *"
      topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      DOMAIN: "otodom-buy"
      CRAWLER_SUFFIX: "/otodom-office-crawler"
      PAGES_SUFFIX: "/otodom-total-pages"
      SOURCE_URL: "https://www.otodom.pl/sprzedaz/lokal/krakow/?search%5Bcity_id%5D=38"
      GATEWAY_URL: "http://gateway.openfaas:8080/function"
      write_timeout: 5m
      read_timeout: 5m
      exec_timeout: 5m
      handler_wait_duration: 1m
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.max: 2
      com.openfaas.scale.min: 1
      app: "function"
  otodom-flat-rent-orchestrator:
    lang: golang-middleware
    handler: ./otodom/orchestrator
    image: e8kor/crawler:otodom-orchestrator
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    annotations:
      schedule: "*/5 * * * *"
      topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      DOMAIN: "otodom-rent"
      CRAWLER_SUFFIX: "/otodom-flat-crawler"
      PAGES_SUFFIX: "/otodom-total-pages"
      SOURCE_URL: "https://www.otodom.pl/wynajem/mieszkanie/krakow/?search%5Bcity_id%5D=38"
      GATEWAY_URL: "http://gateway.openfaas:8080/function"
      write_timeout: 5m
      read_timeout: 5m
      exec_timeout: 5m
      handler_wait_duration: 1m
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.max: 2
      com.openfaas.scale.min: 1
      app: "function"
  otodom-flat-buy-orchestrator:
    lang: golang-middleware
    handler: ./otodom/orchestrator
    image: e8kor/crawler:otodom-orchestrator
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    annotations:
      schedule: "*/5 * * * *"
      topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      DOMAIN: "otodom-buy"
      CRAWLER_SUFFIX: "/otodom-flat-crawler"
      PAGES_SUFFIX: "/otodom-total-pages"
      SOURCE_URL: "https://www.otodom.pl/sprzedaz/mieszkanie/krakow/?search%5Bcity_id%5D=38"
      GATEWAY_URL: "http://gateway.openfaas:8080/function"
      write_timeout: 5m
      read_timeout: 5m
      exec_timeout: 5m
      handler_wait_duration: 1m
    labels:
      com.openfaas.scale.zero: true
      com.openfaas.scale.max: 2
      com.openfaas.scale.min: 1
      app: "function"
  otodom-office-crawler:
    lang: golang-middleware
    handler: ./otodom/office_crawler
    image: e8kor/crawler:otodom-office-crawler
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      SCHEMA_NAME: "office"
      SCHEMA_VERSION: "v0.0.3"
      exec_timeout: 2m
    labels:
      com.openfaas.scale.max: 15
      com.openfaas.scale.min: 10
      app: "function"
  otodom-flat-crawler:
    lang: golang-middleware
    handler: ./otodom/flat_crawler
    image: e8kor/crawler:otodom-flat-crawler
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      SCHEMA_NAME: "flat"
      SCHEMA_VERSION: "v0.0.3"
      exec_timeout: 2m
    labels:
      com.openfaas.scale.max: 15
      com.openfaas.scale.min: 10
      app: "function"
  otodom-total-pages:
    lang: golang-middleware
    handler: ./otodom/total_pages
    image: e8kor/crawler:otodom-total-pages
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
    environment:
      exec_timeout: 2m
    labels:
      com.openfaas.scale.max: 5
      com.openfaas.scale.min: 2
      app: "function"
configuration:
  templates:
    - name: golang-middleware