version: 1.0
provider:
  name: openfaas
functions:
  otodom:
    lang: golang-http
    handler: ./otodom
    image: e8kor/crawler:otodom
    annotations:
      schedule: "*/5 * * * *"
      topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      SOURCE_URL: "https://www.otodom.pl/wynajem/lokal/krakow/?search%5Bcity_id%5D=38"
  persistor:
    lang: golang-http
    handler: ./persistor
    image: e8kor/crawler:persistor
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      PG_HOST: "192.168.0.211"
      PG_PORT: "5432"
    secrets:
      - database-name
      - database-username
      - database-password
configuration:
  templates:
    - name: golang-middleware
    - name: golang-http
    - name: go