version: 1.0
provider:
  name: openfaas
functions:
  otodom-orchestrator:
    lang: golang-http
    handler: ./orchestrator
    image: e8kor/crawler:otodom-orchestrator
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    annotations:
      schedule: "*/5 * * * *"
      topic: cron-function
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      SOURCE_URL: "https://www.otodom.pl/wynajem/lokal/krakow/?search%5Bcity_id%5D=38"
      GATEWAY_URL: "http://gateway.openfaas:8080/function"
      write_timeout: 3m
      read_timeout: 3m
      exec_timeout: 3m
      handler_wait_duration: 1m
  otodom-scrapper:
    lang: golang-http
    handler: ./scrapper
    image: e8kor/crawler:otodom-scrapper
    limits:
      memory: 128Mi
      cpu: 256m
    requests:
      memory: 64Mi
      cpu: 256m
    build_args:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
    environment:
      exec_timeout: "1m"
    labels:
      com.openfaas.scale.min: 6
configuration:
  templates:
    - name: golang-http