name: CI

on: [push]
env:
  DOCKER_REPO: e8kor
  DOCKER_CLI_EXPERIMENTAL: enabled
  GO111MODULE: on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OpenFaaS CLI
        run: |
          curl -sSL https://cli.openfaas.com | sudo sh
      - name: Login to OpenFaaS
        run: |
          echo ${{ secrets.OPENFAAS_PASSWORD }} | faas-cli login --gateway ${{ secrets.OPENFAAS_GATEWAY }} -u ${{ secrets.OPENFAAS_USERNAME }} --password-stdin
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Install buildx as default
        run: |
          docker buildx install
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare core database vendor dependencies
        run: |
          .bin/update_modules
      - name: Get core templates
        run: |
          faas-cli template pull stack
      - name: Build multi platform core functions
        run: |
          faas-cli publish  -f ./base.yml -f ./rent_flat.yml -f ./rent_office.yml  --platforms linux/arm,linux/arm64
      - name: deploy core functions
        if: success() && github.ref == 'refs/heads/main'
        run: |
          faas-cli deploy -g ${{ secrets.OPENFAAS_GATEWAY }}
